"""Bank coding rules.

A rule maps a bank line to an account code (and optionally a tax type and
contact). Rules are ordered by priority, then by specificity, and the first
match wins. Every suggestion records which rule produced it, so a wrong code
can be traced to the rule that caused it instead of being a black box.

Rules come from two places:

* **Explicit** rules the user writes (or that ship as sensible defaults).
* **Learned** rules derived from how similar transactions were coded before.
  These are generated by :func:`learn_rules` and always carry a lower priority
  than explicit ones, so a hand-written rule can never be overridden by a
  pattern inferred from history.
"""

from __future__ import annotations

import json
import re
from dataclasses import asdict, dataclass, field
from decimal import Decimal
from pathlib import Path
from typing import Any

from .models import BankLine
from .money import to_money


class Direction:
    """Which side of the bank a rule applies to."""

    IN = "in"
    OUT = "out"
    ANY = "any"


@dataclass(frozen=True, slots=True)
class Rule:
    """A single coding rule."""

    name: str
    account_code: str
    contains: tuple[str, ...] = ()
    regex: str = ""
    direction: str = Direction.ANY
    min_amount: Decimal | None = None
    max_amount: Decimal | None = None
    tax_type: str = ""
    contact_name: str = ""
    priority: int = 100
    source: str = "explicit"  # explicit | learned | default

    def matches(self, line: BankLine) -> bool:
        """True if every configured condition holds for this line."""
        if self.direction == Direction.IN and not line.is_credit:
            return False
        if self.direction == Direction.OUT and not line.is_debit:
            return False

        magnitude = abs(line.amount)
        if self.min_amount is not None and magnitude < self.min_amount:
            return False
        if self.max_amount is not None and magnitude > self.max_amount:
            return False

        haystack = f"{line.description} {line.reference}".lower()
        # All terms must be present: "uber eats" should not fire on a rule
        # written for "uber" trips if the rule lists both words.
        if self.contains and not all(term.lower() in haystack for term in self.contains):
            return False
        if self.regex:
            try:
                if not re.search(self.regex, haystack, re.IGNORECASE):
                    return False
            except re.error:
                # A malformed user regex must not take down the whole run.
                return False
        # A rule with no conditions at all would match everything; refuse it.
        return bool(self.contains or self.regex or self.min_amount is not None or self.max_amount is not None)

    @property
    def specificity(self) -> int:
        """How narrow this rule is; ties in priority are broken by this."""
        score = sum(len(term) for term in self.contains) + (len(self.regex) * 2)
        if self.direction != Direction.ANY:
            score += 5
        if self.min_amount is not None or self.max_amount is not None:
            score += 5
        return score

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data["contains"] = list(self.contains)
        for key in ("min_amount", "max_amount"):
            if data[key] is not None:
                data[key] = str(data[key])
        return data

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Rule:
        return cls(
            name=str(data.get("name") or "unnamed"),
            account_code=str(data.get("account_code") or ""),
            contains=tuple(data.get("contains") or ()),
            regex=str(data.get("regex") or ""),
            direction=str(data.get("direction") or Direction.ANY),
            min_amount=to_money(data["min_amount"]) if data.get("min_amount") is not None else None,
            max_amount=to_money(data["max_amount"]) if data.get("max_amount") is not None else None,
            tax_type=str(data.get("tax_type") or ""),
            contact_name=str(data.get("contact_name") or ""),
            priority=int(data.get("priority") or 100),
            source=str(data.get("source") or "explicit"),
        )


@dataclass
class RuleSet:
    """An ordered collection of rules."""

    rules: list[Rule] = field(default_factory=list)

    def ordered(self) -> list[Rule]:
        """Lowest priority number first, then most specific first."""
        return sorted(self.rules, key=lambda r: (r.priority, -r.specificity, r.name))

    def match(self, line: BankLine) -> Rule | None:
        for rule in self.ordered():
            if rule.matches(line):
                return rule
        return None

    def add(self, rule: Rule) -> None:
        self.rules.append(rule)

    def save(self, path: str | Path) -> Path:
        target = Path(path)
        target.parent.mkdir(parents=True, exist_ok=True)
        payload = {"rules": [rule.to_dict() for rule in self.ordered()]}
        target.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
        return target

    @classmethod
    def load(cls, path: str | Path) -> RuleSet:
        target = Path(path)
        if not target.exists():
            return cls()
        try:
            raw = json.loads(target.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise ValueError(f"{target} is not valid JSON: {exc}") from exc
        rows = raw.get("rules") if isinstance(raw, dict) else raw
        return cls(rules=[Rule.from_dict(row) for row in (rows or [])])

    @classmethod
    def defaults(cls) -> RuleSet:
        """A starter set for an Australian small business.

        Account codes follow Xero's default AU chart of accounts. They are a
        starting point to be edited, not gospel — every org customises these.
        """
        return cls(
            rules=[
                Rule("Bank fees", "404", contains=("bank fee",), direction=Direction.OUT,
                     tax_type="BASEXCLUDED", priority=10, source="default"),
                Rule("Account keeping fee", "404", contains=("account fee",), direction=Direction.OUT,
                     tax_type="BASEXCLUDED", priority=10, source="default"),
                Rule("Merchant fees", "404", contains=("merchant fee",), direction=Direction.OUT,
                     tax_type="INPUT", priority=10, source="default"),
                Rule("Interest received", "270", contains=("interest",), direction=Direction.IN,
                     tax_type="BASEXCLUDED", priority=20, source="default"),
                Rule("ATO payment", "820", regex=r"\bato\b|australian taxation", direction=Direction.OUT,
                     tax_type="BASEXCLUDED", priority=15, source="default"),
                Rule("Superannuation", "478", contains=("super",), direction=Direction.OUT,
                     tax_type="BASEXCLUDED", priority=15, source="default"),
                Rule("Wages", "477", regex=r"\b(payroll|wages|salary)\b", direction=Direction.OUT,
                     tax_type="BASEXCLUDED", priority=15, source="default"),
                Rule("Insurance", "433", contains=("insurance",), direction=Direction.OUT,
                     tax_type="INPUT", priority=30, source="default"),
                Rule("Telephone & internet", "489", regex=r"telstra|optus|vodafone|internet",
                     direction=Direction.OUT, tax_type="INPUT", priority=30, source="default"),
                Rule("Electricity", "445", regex=r"\b(agl|origin energy|energy australia)\b",
                     direction=Direction.OUT, tax_type="INPUT", priority=30, source="default"),
                Rule("Rent", "469", contains=("rent",), direction=Direction.OUT,
                     tax_type="INPUT", priority=30, source="default"),
                Rule("Motor vehicle / fuel", "449", regex=r"\b(bp |shell|caltex|ampol|7-eleven)\b",
                     direction=Direction.OUT, tax_type="INPUT", priority=40, source="default"),
                Rule("Subscriptions", "485", regex=r"xero|adobe|microsoft|google|atlassian|aws|dropbox",
                     direction=Direction.OUT, tax_type="INPUT", priority=40, source="default"),
                Rule("Legal & accounting", "441", regex=r"lawyer|legal|solicitor|accountant|conveyanc",
                     direction=Direction.OUT, tax_type="INPUT", priority=40, source="default"),
                Rule("Council rates", "449", regex=r"council|shire of|city of", direction=Direction.OUT,
                     tax_type="BASEXCLUDED", priority=40, source="default"),
            ]
        )


def learn_rules(
    history: list[tuple[BankLine, str]],
    min_occurrences: int = 3,
    priority: int = 500,
) -> list[Rule]:
    """Infer rules from previously coded lines.

    ``history`` is a list of ``(line, account_code)`` pairs. A rule is proposed
    only when a distinctive token from the description was coded to the *same*
    account at least ``min_occurrences`` times and was never coded to a
    different one. Requiring unanimity keeps a merchant that legitimately
    splits across two accounts from producing a confidently wrong rule.
    """
    token_accounts: dict[str, dict[str, int]] = {}
    for line, account_code in history:
        if not account_code:
            continue
        for token in _tokens(line.description):
            token_accounts.setdefault(token, {}).setdefault(account_code, 0)
            token_accounts[token][account_code] += 1

    learned: list[Rule] = []
    for token, accounts in token_accounts.items():
        if len(accounts) != 1:
            continue  # ambiguous: the same token maps to more than one account
        account_code, count = next(iter(accounts.items()))
        if count < min_occurrences:
            continue
        learned.append(
            Rule(
                name=f"Learned: {token} -> {account_code}",
                account_code=account_code,
                contains=(token,),
                priority=priority,
                source="learned",
            )
        )
    learned.sort(key=lambda r: (-len(r.contains[0]), r.name))
    return learned


_STOPWORDS = frozenset(
    ["the", "and", "for", "from", "with", "pay", "payment", "payments", "transfer", "tfr", "direct", "debit", "credit", "eftpos", "visa", "mastercard", "card", "purchase", "au", "aus", "australia", "pty", "ltd", "limited", "inc", "co", "bpay", "osko", "payid", "ref", "receipt", "invoice", "inv", "date", "value", "id", "no", "number", "txn", "transaction", "withdrawal", "deposit"]
)


def _tokens(description: str) -> list[str]:
    """Distinctive lowercase words from a bank narrative.

    Bank descriptions are full of noise — card numbers, dates, terminal ids,
    "EFTPOS", "VISA PURCHASE". Anything numeric, too short, or on the stopword
    list is dropped, leaving the merchant name that actually identifies the
    transaction.
    """
    words = re.findall(r"[a-zA-Z][a-zA-Z'&-]{2,}", description.lower())
    return [w for w in words if w not in _STOPWORDS and len(w) >= 4]
